query ($org: String!, $repo: String!) {
	repository(owner: $org, name: $repo) {
		name
		description
		stargazers {
			stars: totalCount
		}
		issues(last: 5) {
			edges {
				node {
					id
					title
					url
					publishedAt
				}
			}
		}
	}
}
